services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        UID: 1000
        GID: 1000
    container_name: laravel_app
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    dns:
    - 8.8.8.8
    - 1.1.1.1

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    ports:
      - "5057:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: aminelebrini32@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "123456"
      POSTGRES_DB: qconnect
    depends_on:
      - db

  db:
    container_name: laravel_pgsql
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: qconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
